# Global 全局配置
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: images/favicon.ico
snow: true
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
cdn: false
check_update: true

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  categories: /categories/ 
  works: /categories/職業攻略/
  activity: /categories/冒險休閒攻略/
  new: /categories/培養攻略/
  timeAct: /categories/活動副本/
  # friend: /friends/
  sites:
    submenu: true
    fb: https://www.facebook.com/icantw.TY
    baha: https://forum.gamer.com.tw/A.php?bsn=70946
    ds: https://ds.163.com/square/5cde5501d545683c1b49ac67/?type=%E7%83%AD%E9%97%A8%E6%8E%A8%E8%8D%90
    line: https://line.me/ti/g2/wYbF7MMXhFk2gMkciACKCw?utm_source=invitation&utm_medium=link_copy&utm_campaign=default

label:
  index: <i class="fa fa-home"></i>首頁
  categories: <i class="fa fa-th"></i>總目錄
  works: <i class="fa fa-file-o"></i>職業攻略
  activity: <i class="fa fa-file-o"></i>冒險攻略
  new: <i class="fa fa-file-o"></i>培養攻略
  timeAct: <i class="fa fa-file-o"></i>活動副本
  # friend: <i class="fa fa-link"></i>友站連結
  sites:
    submenu: <i class="fa fa-link"></i>友站連結
    fb: 天諭粉絲團
    baha: 巴哈天諭版
    ds: 天諭網易大神
    line: 天諭line社群

# Footer 页脚配置
group_link: 
contact:
  weibo: 
  mail: shela3251@gmail.com
  telegram: 
  twitter: 
  facebook: icantw.TY
  linkedin: 
  fediverse:
    instance: 
    username: 
  github: shela1216
  qrcode: https://line.me/ti/g2/wYbF7MMXhFk2gMkciACKCw?utm_source=invitation&utm_medium=link_copy&utm_campaign=default

  
# Post Page 文章页配置
posts:
  show_cc: false
  donate: false
  share: true
  comments: waline

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: tywarm

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/client/basic.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: https://tywarm-git-master-shela1216.vercel.app/ #后端服务器地址，必填
  visitor: true

# APlayer 左下角音乐播放器
aplayer:
  enabled: false
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 3204190542
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: images/avatar.png

# Fancybox 文章内图片单击放大
fancybox: true
# favicon
favicon:
  small: images/favicon-16x16.png
  medium: images/favicon.ico
  apple_touch_icon: images/apple-touch-icon.png
  
# Search 搜索
search:
  enable: true
  path: search.json
  field: all # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    pic:
      CDN: true # 表示使用 CDN 加载图片
      random_amount: 20 # 表示从1~20
      filename: "images/thumb/thumb_{no}.webp" # 相对于主题根目录，表示文件名的格式, {no} 用以指代随机的编号。
                                              # 如果包含 // 表示使用指定域名的绝对路径（例如第三方图床服务等），那么会忽略 CDN 选项
    createTime: "2018/05/06 17:03:12"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: jSoPcNYYF1B9wL02GBGffrfIK1YTnfDR6E_wwmBBs7I
  baidu: 
  bing: 

#Sitemap
sitemap:
    path: sitemap.xml


# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "友站連結"
    comments: false
    description: "推薦本站友好網站"
    updated: "2021-01-18"
  list:
  - name: "巴哈天諭版"
    bio: ""
    avatar: "../images/logo_1.jpg"
    link: "https://forum.gamer.com.tw/A.php?bsn=70946"
  - name: "天諭手遊台港澳官網"
    bio: ""
    link: "https://www.icantw.com/event/TyWarm"
    avatar: "../images/logo_2.png"
  - name: "天諭手遊Line討論社群"
    bio: ""
    avatar: "https://i.imgur.com/KQsGrBO.jpg"
    link: "https://line.me/ti/g2/wYbF7MMXhFk2gMkciACKCw?utm_source=invitation&utm_medium=link_copy&utm_campaign=default"
  # - name: "尚品代儲"
  #   bio: "123456"
  #   avatar: "../images/avatar.png"
  #   link: "#"
  # - name: "YT阿萬"
  #   bio: "喵喵~"
  #   avatar: "../images/avatar.png"
  #   link: "#"
  verify: true # 验证每个友链的可访问性，炸了会有提示
